name: Project1

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests  # Add more steps as needed
        run: |
          # Add commands to run tests or other tasks
